
name: Build & Tests & Deploy en Spring Boot con Matrices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Realizando Test con Java $${{ matrix.java }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       os: [ubuntu-latest, windows-latest]
       java: [25]
    steps:
    - name: Checkout del c贸digo (clonando...)
      uses: actions/checkout@v4
    - name: Set up JDK 17 ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Cache de paquetes maven
      uses: actions/cache@v5.0.3
      with:
       path: ~/.m2/repository
       key: $ {{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
         $ {{ runner.os }}-maven-
    - name: Build y Test
      run: ./mvnw clean verify
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout del c贸digo (clonando...)
      uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: 25
        distribution: 'temurin'
        cache: maven
    - name: Cache de paquetes maven
      uses: actions/cache@v5.0.3
      with:
       path: ~/.m2/repository
       key: ubuntu-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
         ubuntu-maven
    - name: Compilar aplicaci贸n
      run: ./mvnw clean package -DskipTests
    - name: Deploy a producci贸n
      run: |
        echo "Deploying..."
        # Ejemplo usando SCP para subir el jar generado
        # scp target/*.jar usarios@host:/ruta/destino
        3 o enviar a AWS o Bucket
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
