# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Tests en Spring Boot con Matrices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       os: [ubuntu-latest, windows]
       java: [24,25]
    steps:
    - name: Checkout del c√≥digo (clonando...)
      uses: actions/checkout@v4
    - name: Set up JDK 17 ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Cache de paquetes maven
      uses: actions/cache@v5.0.3
      with:
       path: ~/.m2/repository
       key: $ {{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
         $ {{ runner.os }}-maven-
    - name: Build y Test
      run: ./mvnw clean verify
